### PR TITLE
README support osm/osm-edge

### PR DESCRIPTION
**Pull request by cybwan**
README support osm/osm-edge
signed-off-by: cybwan <baili@flomesh.io>

### CODE REVIEW

**Review by windsonsea — APPROVED** [review]
Thanks, lgtm

**Comment by windsonsea** [comment]
Hi @cybwan , would you like to write a blog, in which you can tell the story when, why, how about the integration with OSM/OSM-edge.

**Comment by cybwan** [comment]
>
OSM Edge's demo:
https://github.com/cybwan/osm-edge-start-demo/blob/main/demo/merbridge/README.zh.md

Need rebuild latest images.

**Comment by kebe7jun** [comment]
I will create a new release v0.8.0, the main inclusion is the osm support.
Let us know if you have any ideas.
Also, the latest image has been built (from the main branch).

**Comment by cybwan** [comment]
> 
@windsonsea Welcome!

**Comment by cybwan** [comment]
Just i update the demo.

**Pull request merged**
